language: generic
sudo: required
services:
    - docker
before-install:
    - docker build -t aslam/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true USERNAME/docker-react npm run test